# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2 # Read the Docs에서 사용하는 구성 파일의 버전

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04 # 빌드에 사용할 운영체제
  tools:
    python: "3.12" # 사용할 Python 버전
# MkDocs 빌드 설정 파일 위치 지정
mkdocs:
  configuration: mkdocs.yml # 문서 빌드를 위한 MkDocs 구성 파일 경로

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt # 설치할 패키지 목록이 있는 파일 경로