site_name: Altibase Documentation
site_url: https://soyoon-choi-mkdocs-trial.readthedocs-hosted.com/en/7.1/

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    accent: custom
  language: en
  favicon: img/favicon.ico
  logo: img/logo_w.png
  features:
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - search.suggest
    - search.share
    - search.boost
    - toc.follow

extra:
  alternate:
    - name: English
      link: /en/7.1/
      lang: en
    - name: Korean
      link: /ko/7.1/
      lang: ko
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ALTIBASE/Documents/tree/master/Manuals/Altibase_7.1/eng
    - icon: fontawesome/solid/house
      link: https://www.altibase.com/en/index.php
    - icon: fontawesome/solid/phone
      link: http://support.altibase.com/en/
      name: Altibase Support Center
  analytics:
    provider: google
    property: G-QGH6FBLTP5
  generator: false

copyright: © 1999-2024 Altibase Corp.

extra_css:
  - custom/style.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search:
      lang: 
        - en
        - ko
      separator: '[\s\-\_,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;'
  - exclude-search:
      exclude:
        - SUMMARY.md
  - literate-nav:
      nav_file: SUMMARY.md
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "#"
      toc_depth: 4
  - pymdownx.caret:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg